# Generated by Django 3.1.6 on 2021-02-16 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=500)),
                ('created_with', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('Addresses', models.CharField(max_length=30)),
                ('cell_mobile_phone', models.CharField(max_length=30)),
                ('Whatsapp_number', models.CharField(max_length=30)),
                ('optionai_contact', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='phone',
            fields=[
                ('phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('ram', models.CharField(max_length=30)),
                ('storage', models.CharField(max_length=30)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('fuel_type', models.CharField(max_length=30)),
                ('engine_size', models.CharField(max_length=30)),
                ('make', models.CharField(max_length=30)),
                ('year_of_use', models.CharField(max_length=30)),
                ('year_of_manufacture', models.CharField(max_length=30)),
                ('body_type', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('millage', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('dscription', models.CharField(max_length=300)),
                ('created_with', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.owner')),
            ],
        ),
    ]
