# Generated by Django 3.1.6 on 2021-02-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='transmition',
            field=models.CharField(choices=[('manual', 'manual'), ('automatic', 'automatic')], default='manual', max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('Single-cab', 'Single-cab'), ('double-cab', 'double-cab'), ('sedan', 'sedan'), ('hatchback', 'hatchback'), ('truck', 'truck'), ('suv', 'suv'), ('Any', 'Any')], default='any', max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'petrol'), ('deasel', 'diesel')], default='petrol', max_length=30),
        ),
    ]
