# Generated by Django 3.1.6 on 2021-02-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210218_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Central_Locking',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='yes', max_length=30),
        ),
        migrations.AddField(
            model_name='car',
            name='air_conditioner',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='yes', max_length=30),
        ),
        migrations.AddField(
            model_name='car',
            name='cd_Player',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='yes', max_length=30),
        ),
        migrations.AddField(
            model_name='car',
            name='power_steering',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='yes', max_length=30),
        ),
    ]
