# Generated by Django 3.1.6 on 2021-02-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210218_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Central_Locking',
            new_name='antilock_braking_system',
        ),
        migrations.AddField(
            model_name='car',
            name='brake_assist',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='yes', max_length=30),
        ),
        migrations.AddField(
            model_name='car',
            name='driver_airbag',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='yes', max_length=30),
        ),
        migrations.AddField(
            model_name='car',
            name='leather_seats',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='yes', max_length=30),
        ),
        migrations.AddField(
            model_name='car',
            name='power_door_locks',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='yes', max_length=30),
        ),
        migrations.AddField(
            model_name='car',
            name='power_windows',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='yes', max_length=30),
        ),
    ]
