# Generated by Django 3.1.6 on 2021-02-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20210218_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='central_locking',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='yes', max_length=30),
        ),
        migrations.AddField(
            model_name='car',
            name='fog_lamps',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='yes', max_length=30),
        ),
    ]
