# Generated by Django 3.1.6 on 2021-02-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20210218_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(choices=[('CAR', 'CAR'), ('Mazda', 'Mazda'), ('Ford', 'Ford'), ('Nissan', 'Nissan'), ('Toyota', 'Toyota'), ('Bmw', 'Bmw'), ('Audi', 'Audi'), ('Mercedes benz', 'Mercedes benz'), ('Vw', 'Vw'), ('Honda', 'Honda'), ('Pegeot', 'Pegeot'), ('Pocshe', 'Posche')], default='car', max_length=30),
        ),
    ]
