# Generated by Django 3.1.6 on 2021-02-20 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20210218_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='image',
            new_name='car_img',
        ),
    ]
