# Generated by Django 3.1.6 on 2021-02-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20210220_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_img2',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_img3',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_img4',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_img5',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_img6',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
