# Generated by Django 3.1.6 on 2021-02-20 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20210220_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audi', models.CharField(choices=[('petrol', 'petrol'), ('deasel', 'diesel')], default='petrol', max_length=30)),
                ('Bmw', models.CharField(choices=[('1 siries', '1 siries'), ('2 siries', '2 siries'), ('3 siries', '3 siries')], default='petrol', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.maker'),
        ),
    ]
