# Generated by Django 3.1.6 on 2021-02-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20210220_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_img2',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_img3',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_img4',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_img5',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_img6',
        ),
    ]
